# Generated by Django 4.2.3 on 2023-07-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compelted',
            new_name='completed',
        ),
    ]
